## Overview of STOs

Script Table Operators (STOs) are a very powerful in-database option. 

#### map_row

It processes records on a row by row basis, in parallel across all AMPs in Teradata. Perfect for feature transformation. It automatically "chunks" the partitions behind the scenes which means you can process very large partitions using map_row without using much memory and without the risk of running out of memory due to having to keep the entire partition in memory.

If you are faimilar with `map` in functional programming, this is more or less what it is. It takes 1 input (a row) and returns 1 output (a row).


#### map_partition

It processes data on a partition by partition basis, in parallel across all AMPs in Teradata. This is well suited to partitioned modelling, where we want to train an individual model on each partition of the data. 

This is similar to `flat map` in functional programming in that it takes N rows (where N is the number of rows in the partition) and returns 0 or more rows. That is, it can return a different number of rows than it takes. There are a number of very interesting applications for this. 


#### Notes & Recommendations

Things to be aware of when using map_row/map_partition with teradataml

- Python versions must match between client and in-vantage
- The version of dill on both client and in-vantage must match
- Whatever libraries you use must have matching versions between client and in-vantage
- You must have the correct permissions to both install and delete files in Teradata
- Know what the ScriptMemLimit is. This determines what memory each AMP has in Teradata for Scripts. Default is 32MB!


Depending on the STO version and TD Version you have installed, you will be using different python versions and library versions. There will be python 3.7 and many new libraries (including the support for ONNX libraries) and upgrades to current library versions with the latest service pack. However, the python 3.7 change is very important to highlight along with the library version changes. If you save models or any pickle files in python, it is very dependent. Both the python version and the library versions. Therefore you need to be aware that any models you have saved using this verion will break / stop working if an upgrade to Teradata Vantage happens. So, what are our recommendations for using teradataml.

- map_row recommended for advanced feature engineering that you cannot do with SQL/VAL etc.
- map_partition recommended for partitioned processing like partitioned model training/evaluation/scoring
- Save partition models as ONNX or PMML
- We can execute PMML via IVSM / PMMLPredict
- We can execute ONNX (once library available) in either STO or via the ONNXPredict


#### Checking Versions

```python
from aoa.sto.util import collect_sto_versions, check_sto_version

collect_sto_versions()
check_sto_version()
```


#### Logging

If you want to enable query logging as a whole, do this at the sqlalchemly level
```python
import logging
logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)
```

If you want to log just the MLE queries you can set

```python
display.print_sqlmr_query = True
```

In [1]:
from teradataml import DataFrame, create_context, get_connection, load_example_data
import getpass

create_context(host="3.238.151.85", username="AOA_DEMO", password=getpass.getpass("password"))

password········

Engine(teradatasql://AOA_DEMO:***@3.238.151.85)

In [3]:
load_example_data("dataframe", "admissions_train")

WARNING: Skipped loading table admissions_train since it already exists in the database.

In [7]:
df = DataFrame('admissions_train')
df.head()

   masters   gpa     stats programming  admitted
id
3       no  3.70    Novice    Beginner         1
5       no  3.44    Novice      Novice         0
6      yes  3.50  Beginner    Advanced         1
7      yes  2.33    Novice      Novice         1
9       no  3.82  Advanced    Advanced         1
10      no  3.71  Advanced    Advanced         1
8       no  3.60  Beginner    Advanced         1
4      yes  3.50  Beginner      Novice         1
2      yes  3.76  Beginner    Beginner         0
1      yes  3.95  Beginner    Beginner         0

### Modify Column with map_row 

A simple example which shows how to modify an existing column in a dataset

In [11]:
df.map_row?

In [20]:
def increase_gpa(row, p):
    row['gpa'] = row['gpa'] + row['gpa'] * p
    return row

df = DataFrame('admissions_train')
df = df.map_row(lambda row: increase_gpa(row, 0.2))
df.head()

   masters    gpa     stats programming  admitted
id
3       no  4.440    Novice    Beginner         1
5       no  4.128    Novice      Novice         0
6      yes  4.200  Beginner    Advanced         1
7      yes  2.796    Novice      Novice         1
9       no  4.584  Advanced    Advanced         1
10      no  4.452  Advanced    Advanced         1
8       no  4.320  Beginner    Advanced         1
4      yes  4.200  Beginner      Novice         1
2      yes  4.512  Beginner    Beginner         0
1      yes  4.740  Beginner    Beginner         0

### New column derived from others via map_row 

A simple example which shows how to return a new column for a dataset

In [21]:
from teradatasqlalchemy.types import INTEGER, VARCHAR, BIGINT, DECIMAL, CLOB
from collections import OrderedDict
import numpy as np

def increase_gpa(row):
    new_gpa = row['gpa'] + row['gpa'] * 0.2
    return np.array([row['id'], new_gpa])

df = DataFrame('admissions_train')
df = df.map_row(lambda row: increase_gpa(row), 
                returns=OrderedDict([("id", INTEGER()),
                                     ("new_gpa", DECIMAL())]))
df.head()

   new_gpa
id
3    4.440
5    4.128
6    4.200
7    2.796
9    4.584
10   4.452
8    4.320
4    4.200
2    4.512
1    4.740

### Append new column derived from others via map_row 

A simple example which shows how to append a new column to a dataset

In [23]:
def increase_gpa(row):
    row["new_gpa"] = row['gpa'] + row['gpa'] * 0.2
    return row

df = DataFrame('admissions_train')

returns = OrderedDict(zip(df.columns, [col.type for col in df._metaexpr.c]))
returns["new_gpa"] = DECIMAL()

df = df.map_row(lambda row: increase_gpa(row), returns=returns)
df.head()

   masters   gpa     stats programming  admitted new_gpa
id
3       no  3.70    Novice    Beginner         1   4.440
5       no  3.44    Novice      Novice         0   4.128
6      yes  3.50  Beginner    Advanced         1   4.200
7      yes  2.33    Novice      Novice         1   2.796
9       no  3.82  Advanced    Advanced         1   4.584
10      no  3.71  Advanced    Advanced         1   4.452
8       no  3.60  Beginner    Advanced         1   4.320
4      yes  3.50  Beginner      Novice         1   4.200
2      yes  3.76  Beginner    Beginner         0   4.512
1      yes  3.95  Beginner    Beginner         0   4.740

In [ ]:

def increase_gpa(row):
    new_gpa = row['gpa'] + row['gpa'] * 0.2
    return np.array([row['id'], new_gpa])

df = DataFrame(query="SELECT * FROM admissions_train")
df = df.map_row(lambda row: increase_gpa(row), 
                returns=OrderedDict([("id", INTEGER()),
                                     ("new_gpa", DECIMAL())]))

df = DataFrame(query=f"""
SELECT * FROM IVSM.IVSM_SCORE (
    on (SELECT * FROM {df._table_name}) AS DataTable
    on (SELECT model_id, model FROM aoa_ivsm_models WHERE model_version = 'a8dca689-d932-483d-b109-8b5e2d965975') AS ModelTable DIMENSION
    using
        ModelID('03c9a01f-bd46-4e7c-9a60-4282039094e6')
        ColumnsToPreserve('PatientId')
        ModelType('PMML')
) sc;
""")

### Train a model on a parition of the data using map_partition

A simple example which shows how to train a model per partition of the data

In [29]:
from sklearn.linear_model import LogisticRegression
import base64
import dill

def train_partition_model(partition):
    # read all of the rows into memory (we can also process in chunks)
    rows = partition.read()
    
    # return if partition has no data
    if rows is None or len(rows) == 0:
        return None
    
    X = rows[["masters", "gpa", "stats", "programming"]]
    Y = rows[["admitted"]]
    
    clf = LogisticRegression()
    clf = clf.fit(X[["gpa"]], Y)
    
    partition_id = rows.partition_id.iloc[0]
    
    # we have to convert the model to base64 to store in a CLOB column (can't use BLOB with STOs)
    artefact = base64.b64encode(dill.dumps(clf))
    
    # here we return 1 row per partition - basically, the trained model for that partition
    return np.array([[partition_id, 'my_model_version', artefact]])


# lets add a synthetic partition_id column
df = DataFrame(query="SELECT MOD(id, 2) as partition_id, T.* FROM admissions_train T")

df = df.map_partition(lambda partition: train_partition_model(partition),
                      data_partition_column="partition_id",
                      returns=OrderedDict(
                                    [('partition_id', VARCHAR(255)),
                                     ('model_version', VARCHAR(255)),
                                     ('model_artefact', CLOB())]))
df.head()

                 model_version                                     model_artefact
partition_id
1             my_model_version  gANjc2tsZWFybi5saW5lYXJfbW9kZWwubG9naXN0aWMKTG...
0             my_model_version  gANjc2tsZWFybi5saW5lYXJfbW9kZWwubG9naXN0aWMKTG...

In [28]:
df = DataFrame(query="""
SELECT partition_id, count(*) as c FROM (
    SELECT MOD(id, 2) as partition_id, T.* FROM admissions_train T) s 
    GROUP BY partition_id
""")
df.head()

   partition_id   c
0             1  20
1             0  20

### How to validate library versions

In [30]:
from aoa.sto.util import collect_sto_versions, check_sto_version

collect_sto_versions()

{'python_version': '3.6.7 (default, Nov 21 2019, 00:48:33)  [GCC 4.8.5]',
 'packages': {'cycler': '0.10.0',
  'PySAL': '1.14.4.post2',
  'pyflux': '0.4.15',
  'webencodings': '0.5.1',
  'ipykernel': '5.1.0',
  'entrypoints': '0.2.3',
  'Keras-Preprocessing': '1.0.5',
  'plotly': '3.7.1',
  'execnet': '1.5.0',
  'more-itertools': '4.3.0',
  'tornado': '5.1.1',
  'backcall': '0.1.0',
  'slackclient': '1.3.0',
  'coverage': '4.5.2',
  'jedi': '0.13.1',
  'statsmodels': '0.9.0',
  'requests': '2.20.1',
  'Bottleneck': '1.2.1',
  'murmurhash': '1.0.1',
  'scikit-learn': '0.20.3',
  'apipkg': '1.5',
  'jupyter-client': '5.2.3',
  'psutil': '5.4.8',
  'elasticsearch': '6.3.1',
  'pycparser': '2.19',
  'mpmath': '1.0.0',
  'prompt-toolkit': '2.0.7',
  'pluggy': '0.9.0',
  'nltk': '3.4',
  'wheel': '0.32.3',
  'numexpr': '2.6.8',
  'yt': '3.5.1',
  'Pygments': '2.2.0',
  'jdcal': '1.4',
  'pexpect': '4.6.0',
  'ruamel.yaml': '0.15.42',
  'packaging': '18.0',
  'PyYAML': '3.13',
  'plac': '0.9.6',
  'PuLP': '1.6.9',
  'qtconsole': '4.4.3',
  'pytest-forked': '0.2',
  'tabulate': '0.8.2',
  'scipy': '1.2.1',
  'pytest-cov': '2.6.0',
  'chardet': '3.0.4',
  'urllib3': '1.24.1',
  'Pillow': '5.3.0',
  'widgetsnbextension': '3.4.2',
  'numpy': '1.16.1',
  'decorator': '4.3.0',
  'dill': '0.2.8.2',
  'defusedxml': '0.5.0',
  'six': '1.11.0',
  'idna': '2.7',
  'ptyprocess': '0.6.0',
  'algopy': '0.5.7',
  'bleach': '3.0.2',
  'thinc': '6.12.0',
  'Keras-Applications': '1.0.6',
  'cymem': '2.0.2',
  'pandasql': '0.7.3',
  'pathlib2': '2.3.2',
  'pyshp': '2.0.1',
  'prometheus-client': '0.4.2',
  'pyparsing': '2.3.0',
  'gmpy2': '2.0.8',
  'attrs': '18.2.0',
  'nbformat': '4.4.0',
  'ipython': '7.1.1',
  'scandir': '1.9.0',
  'SQLAlchemy': '1.3.3',
  'Jinja2': '2.10',
  'tqdm': '4.28.1',
  'mpc': '0.0.3',
  'ujson': '1.35',
  'pytest-timeout': '1.3.3',
  'msgpack-numpy': '0.4.3.2',
  'cffi': '1.11.5',
  'terminado': '0.8.1',
  'toolz': '0.9.0',
  'numdifftools': '0.9.20',
  'isort': '4.3.4',
  'cytoolz': '0.9.0.1',
  'singledispatch': '3.4.0.3',
  'Cython': '0.29',
  'MarkupSafe': '1.1.0',
  'preshed': '2.0.1',
  'pandas': '0.24.2',
  'simpy': '3.0.11',
  'patsy': '0.5.1',
  'Click': '7.0',
  'python-dateutil': '2.7.5',
  'sqlparse': '0.2.4',
  'h5py': '2.8.0',
  'matplotlib': '3.0.2',
  'ipython-genutils': '0.2.0',
  'beautifulsoup4': '4.6.3',
  'networkx': '2.2',
  'imageio': '2.4.1',
  'mistune': '0.8.4',
  'pip': '19.0.3',
  'kiwisolver': '1.0.1',
  'msgpack': '0.5.6',
  'parso': '0.3.1',
  'testpath': '0.4.2',
  'jupyter-core': '4.4.0',
  'xgboost': '0.82',
  'regex': '2018.1.10',
  'Keras': '2.2.4',
  'pickleshare': '0.7.5',
  'seaborn': '0.9.0',
  'notebook': '5.7.2',
  'simplegeneric': '0.8.1',
  'wordcloud': '1.5.0',
  'jupyter-console': '6.0.0',
  'pytest-xdist': '1.28.0',
  'traitlets': '4.3.2',
  'Theano': '1.0.3',
  'subprocess32': '3.5.3',
  'jsonschema': '2.6.0',
  'python-Levenshtein': '0.12.0',
  'elasticsearch-dsl': '6.3.0',
  'retrying': '1.3.3',
  'hyperlink': '18.0.0',
  'pytz': '2018.7',
  'nose': '1.3.7',
  'nbconvert': '5.4.0',
  'websocket-client': '0.54.0',
  'wrapt': '1.10.11',
  'sympy': '1.3',
  'pytest': '4.4.0',
  'Send2Trash': '1.5.0',
  'pyzmq': '17.1.2',
  'jupyter': '1.0.0',
  'pandocfilters': '1.4.2',
  'wcwidth': '0.1.7',
  'py': '1.7.0',
  'spacy': '2.0.16',
  'certifi': '2018.11.29',
  'atomicwrites': '1.2.1',
  'PyWavelets': '1.0.1',
  'rope': '0.11.0',
  'itsdangerous': '1.1.0',
  'ipywidgets': '7.4.2',
  'teradata': '15.10.0.21',
  'setuptools': '40.6.2'}}